version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: db-casadocodigo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: casa-do-codigo-kotlin
    ports:
      - "5432:5432"