micronaut:
  application:
    name: casaDoCodigoKotlin
datasources:
  default:
    url: jdbc:mysql://localhost:3306/casa_do_codigo_kotlin
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
jpa.default.properties.hibernate.hbm2ddl.auto: update
